#!/usr/bin/env python3
"""Generate compiled Bullet spEffectId3 allowlist from Bullet.csv."""

from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CSV_PATH = ROOT / "Bullet.csv"
OUT_PATH = ROOT / "include" / "bullet_sp_effect_allowlist_generated.h"
EXPECTED_UNIQUE_IDS = 6119


def parse_bullet_ids(csv_path: Path) -> list[int]:
    text = csv_path.read_text(encoding="utf-8-sig")
    ids: set[int] = set()
    for line_no, line in enumerate(text.splitlines(), start=1):
        stripped = line.strip()
        if not stripped or stripped.startswith("ID,"):
            continue
        match = re.match(r"^(\d+)", stripped)
        if not match:
            raise ValueError(f"{csv_path}:{line_no}: could not parse bullet id from {stripped!r}")
        ids.add(int(match.group(1)))
    return sorted(ids)


def emit_header(ids: list[int], out_path: Path) -> None:
    out_path.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "#pragma once",
        "",
        "#include <cstddef>",
        "#include <cstdint>",
        "",
        "// Generated by tools/generate_bullet_allowlist.py from Bullet.csv.",
        "// Do not edit manually.",
        f"inline constexpr std::size_t kDestinedDeathBulletAllowlistCount = {len(ids)};",
        "",
        "inline constexpr int32_t kDestinedDeathBulletAllowlist[] = {",
    ]
    for index, bullet_id in enumerate(ids):
        suffix = "," if index + 1 < len(ids) else ""
        lines.append(f"    {bullet_id}{suffix}")
    lines.extend(
        [
            "};",
            "",
        ]
    )
    out_path.write_text("\n".join(lines), encoding="utf-8", newline="\n")


def main() -> int:
    if not CSV_PATH.is_file():
        print(f"error: missing {CSV_PATH}", file=sys.stderr)
        return 1

    ids = parse_bullet_ids(CSV_PATH)
    if len(ids) != EXPECTED_UNIQUE_IDS:
        print(
            f"error: expected {EXPECTED_UNIQUE_IDS} unique bullet ids, found {len(ids)}",
            file=sys.stderr,
        )
        return 1

    emit_header(ids, OUT_PATH)
    print(f"Wrote {len(ids)} bullet ids to {OUT_PATH}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
